AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template with resources necessary to perform instance auto-restart on Outposts servers

Parameters:
  StackName:
    Type: String
    Description: "Name of the CloudFormation stack"
  SourceOutpostId:
    Type: String
    Description: "ID of the source outpost"
  NotificationEmail:
    Type: String
    Description: "Email address for SNS notifications"

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Description: 'KMS key for encrypting SNS topic data'
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:*'
            Resource: '*'
          - Sid: Allow Cloudwatch to use the key
            Effect: Allow
            Principal:
              Service: cloudwatch.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
              - kms:DescribeKey
            Resource: '*'
          - Sid: Allow Cloudwatch Logs to use the key
            Effect: Allow
            Principal:
              Service: logs.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'

  KMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${AWS::StackName}-kmskey'
      TargetKeyId: !Ref KMSKey

  LambdaSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Outpost Server Notification"
      KmsMasterKeyId: !Ref KMSKey

  EmailSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Outpost Server Email Notification"
      KmsMasterKeyId: !Ref KMSKey

  EmailSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref NotificationEmail
      TopicArn: !Ref EmailSNSTopic

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole

  LambdaExecutionPolicy:
    Type: AWS::IAM::Policy
    DependsOn: LambdaFunction
    Properties:
      PolicyName: LambdaExecutionPolicy
      Roles:
        - !Ref LambdaExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:DescribeStacks
            Resource: !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*'
          - Effect: Allow
            Action:
              - cloudwatch:DescribeAlarmHistory
            Resource: !Sub 'arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:OutpostDownAlarm-${AWS::StackName}'
          - Effect: Allow
            Action:
              - ec2:RunInstances
              - ec2:CreateTags
              - ec2:DescribeInstances
              - ec2:DescribeLaunchTemplates
            Resource: '*'
          - Effect: Allow
            Action:
              - elasticloadbalancing:DescribeTargetGroups
              - elasticloadbalancing:DescribeTargetHealth
            Resource: '*'
          - Effect: Allow
            Action:
              - elasticloadbalancing:RegisterTargets
              - elasticloadbalancing:DeregisterTargets
            Resource: !Sub 'arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/*/*'
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !GetAtt LambdaFunction.Arn
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'
          - Effect: Allow
            Action:
              - outposts:ListAssets
            Resource: !Sub 'arn:aws:outposts:${AWS::Region}:${AWS::AccountId}:outpost/${SourceOutpostId}'
          - Effect: Allow
            Action:
              - ssm:GetParameters
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'
          - Effect: Allow
            Action:
              - sts:GetCallerIdentity
            Resource: !Sub 'arn:aws:sts::${AWS::AccountId}:assumed-role/${AWS::StackName}-LambdaExecutionRole/*'
          - Effect: Allow
            Action:
              - sns:Publish
              - sns:Subscribe
              - sns:Unsubscribe
            Resource:
              - !Ref LambdaSNSTopic
              - !Ref EmailSNSTopic
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: !GetAtt KMSKey.Arn

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          STACK_NAME: !Ref StackName
          SOURCE_OUTPOST_ID: !Ref SourceOutpostId
          LAMBDA_SNS_TOPIC_ARN: !Ref LambdaSNSTopic
          EMAIL_SNS_TOPIC_ARN: !Ref EmailSNSTopic

      Code:
        ZipFile: |
          import os
          import boto3
          from botocore.exceptions import ClientError, WaiterError
          
          # Retrieve launch template IDs from CloudFormation stack
          def get_launch_template_ids(stack_name):
            cloudformation = boto3.client("cloudformation")
            try:
              stack_details = cloudformation.describe_stacks(StackName=stack_name)
              outputs = stack_details["Stacks"][0]["Outputs"]
              launch_template_ids = []
              for output in outputs:
                if output["OutputKey"].startswith("LaunchTemplateId"):
                  launch_template_ids.append(output["OutputValue"])
              if not launch_template_ids:
                raise Exception(f"Launch template IDs not found in stack {stack_name}.")
              return launch_template_ids
            except Exception as e:
              print(f"Error retrieving launch template IDs: {str(e)}")
              return None
          
          # Update ALB if ALB exists on instances on the existing Outposts server
          def update_alb_target_group(source_outpost_id, new_instance_ids):
            ec2 = boto3.client('ec2')
            elbv2 = boto3.client('elbv2')
        
            try:
              # Find target group for Outpost instances
              target_groups = elbv2.describe_target_groups()
              target_group_arn = None
              existing_instances = []
        
              for tg in target_groups['TargetGroups']:
                health = elbv2.describe_target_health(TargetGroupArn=tg['TargetGroupArn'])
                tg_instances = [target['Target']['Id'] for target in health['TargetHealthDescriptions']]
                
                # Check if any of the instances in the target group are also on the Outpost
                outpost_arn = f"arn:aws:outposts:{ec2.meta.region_name}:{boto3.client('sts').get_caller_identity()['Account']}:outpost/{source_outpost_id}"
                response = ec2.describe_instances(InstanceIds=tg_instances, Filters=[{'Name': 'outpost-arn', 'Values': [outpost_arn]}])
        
                if response['Reservations']:
                  target_group_arn = tg['TargetGroupArn']
                  existing_instances = [instance['InstanceId'] for reservation in response['Reservations'] for instance in reservation['Instances']]
                  break
        
              if not target_group_arn:
                return "No ALB target group was found for the Outpost instances."
        
              print(f"Found target group: {target_group_arn}")
              print(f"Existing instances in target group: {existing_instances}")
        
              # Register new instances to the target group
              if new_instance_ids:
                  print(f"Attempting to register new instances: {new_instance_ids}")
                  elbv2.register_targets(
                      TargetGroupArn=target_group_arn,
                      Targets=[{'Id': id} for id in new_instance_ids]
                  )
                  print(f"Successfully registered new instances: {new_instance_ids}")
        
              # Deregister old instances from the target group
              if existing_instances:
                  print(f"Attempting to deregister old instances: {existing_instances}")
                  elbv2.deregister_targets(
                      TargetGroupArn=target_group_arn,
                      Targets=[{'Id': id} for id in existing_instances]
                  )
                  print(f"Successfully deregistering old instances: {existing_instances}")
        
              # Verify the current state of the target group
              current_health = elbv2.describe_target_health(TargetGroupArn=target_group_arn)
              current_instances = [target['Target']['Id'] for target in current_health['TargetHealthDescriptions']]
              print(f"Current instances in target group: {current_instances}")
        
              return f"New instances registered and old instances deregistered from target group {target_group_arn}. Current instances: {current_instances}."
            except ClientError as e:
              return f"Error updating ALB target group: {str(e)}"
          
          # Wait for newly launched instances to enter 'running' state
          def wait_for_instances_running(instance_ids, max_attempts=30):
            ec2 = boto3.client('ec2')
            waiter = ec2.get_waiter('instance_running')
            try:
              print(f"Waiting for instances {instance_ids} to enter 'running' state")
              waiter.wait(
                InstanceIds=instance_ids,
                WaiterConfig={
                  'Delay': 15,
                  'MaxAttempts': max_attempts
                }
              )
              print(f"All instances are now in 'running' state")
              return True
            except WaiterError as e:
              print(f"Not all instances are in 'running' state after {max_attempts} attempts: {e}")
              return False
          
          # Main Lambda handler
          def lambda_handler(event, context):
              stack_name = os.getenv("STACK_NAME")
              source_outpost_id = os.getenv("SOURCE_OUTPOST_ID")
              lambda_sns_topic_arn = os.getenv("LAMBDA_SNS_TOPIC_ARN")
              email_sns_topic_arn = os.getenv("EMAIL_SNS_TOPIC_ARN")
          
              print(f"Received event: {event}")
              print(f"Stack Name: {stack_name}")
              print(f"Outpost ID: {source_outpost_id}")
              print(f"Lambda SNS Topic ARN: {lambda_sns_topic_arn}")
              print(f"Email SNS Topic ARN: {email_sns_topic_arn}")
          
              # Check if this is a new alarm state
              cloudwatch = boto3.client('cloudwatch')
              alarm_name = f"OutpostDownAlarm-{stack_name}"
          
              try:
                  alarm_history = cloudwatch.describe_alarm_history(
                      AlarmName=alarm_name,
                      HistoryItemType='StateUpdate',
                      MaxRecords=2
                  )
          
                  if len(alarm_history['AlarmHistoryItems']) >= 2:
                      current_state = alarm_history['AlarmHistoryItems'][0]['HistorySummary']
                      previous_state = alarm_history['AlarmHistoryItems'][1]['HistorySummary']
          
                      # Do not re-alarm if the Outposts server is already in alarm state
                      if 'ALARM' in current_state and 'ALARM' in previous_state:
                          print(f"Alarm {alarm_name} is already in ALARM state. Skipping action.")
                          return
              except ClientError as e:
                  print(f"Error checking alarm history: {e}")
          
              instance_ids = []
              alb_message = ""
          
              try:
                  # Grab launch template IDs to prepare to launch
                  launch_template_ids = get_launch_template_ids(stack_name)
                  if not launch_template_ids:
                    raise Exception("No launch template IDs found.")
          
                  print(f"Retrieved launch template IDs: {launch_template_ids}")
                  ec2 = boto3.client("ec2")
          
                  # Launch an EC2 instance for every launch template ID provided
                  for launch_template_id in launch_template_ids:
                      try:
                          print(f"Launching new instance with launch template ID: {launch_template_id}")
                          launch_response = ec2.run_instances(
                              LaunchTemplate={"LaunchTemplateId": launch_template_id},
                              MinCount=1,
                              MaxCount=1,
                          )
                          instance_id = launch_response["Instances"][0]["InstanceId"]
                          instance_ids.append(instance_id)
                          print(f"Launched instance: {instance_id}")
                      except ClientError as e:
                          print(f"Error launching instance with launch template ID {launch_template_id}: {e}")
                          raise
          
                  print(f"Launching instances: {instance_ids}")
          
                  # Wait for instances to enter 'running' state
                  if not wait_for_instances_running(instance_ids):
                    raise Exception("Timeout waiting for instances to enter 'running' state")
                  print(f"Instances are now in running state: {instance_ids}")
          
                  # Update ALB if ALB exists
                  alb_message = update_alb_target_group(source_outpost_id, instance_ids)
          
                  # Send e-mail via SNS
                  email_sns = boto3.client("sns")
                  try:
                      message = f"Outpost {source_outpost_id} is in alarm state. Instances have successfully begun re-launching: {', '.join(instance_ids)}. {alb_message} Instance status can be monitored on EC2."
                      email_sns.publish(
                          TopicArn=email_sns_topic_arn,
                          Message=message,
                          Subject="Outpost Instance Launch Success"
                      )
                      print(f"Published success message to SNS topic: {message}")
                  except ClientError as e:
                      print(f"Error publishing success message to SNS topic: {e}")
                      raise

              except Exception as e:
                  print(f"Error in lambda_handler: {str(e)}")
          
                  email_sns = boto3.client("sns")
                  try:
                      if instance_ids:
                        message_intro = f"Outpost {source_outpost_id} is in alarm state. Instance re-launch was attempted but failed with error below, though the following instances were successfully launched: {instance_ids}."
                      else:
                        message_intro = f"Outpost {source_outpost_id} is in alarm state. Instance re-launch was attempted but failed with error:"
                      message = f"""{message_intro}
          
          {str(e)}

          Please manually resolve and re-launch.

          Note: In the case of insufficient capacity, the instances may have successfully relaunched but are not associated with an Outpost."""
                      email_sns.publish(
                          TopicArn=email_sns_topic_arn,
                          Message=message,
                          Subject="Outpost Instance Launch Failure"
                      )
                      print(f"Published error message to SNS topic: {message}")
                  except ClientError as e:
                      print(f"Error publishing error message to SNS topic: {e}")
                      raise

      Runtime: python3.8
      Timeout: 900 # Set timeout 15 minutes

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref LambdaSNSTopic

  LambdaSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt LambdaFunction.Arn
      TopicArn: !Ref LambdaSNSTopic

  ConnectedStatusAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm when Outpost is down. Failure means ConnectedStatus is less than 1 for 3 datapoints within 3 minutes"
      AlarmName: !Sub "OutpostDownAlarm-${AWS::StackName}"
      Namespace: "AWS/Outposts"
      MetricName: "ConnectedStatus"
      Dimensions:
        - Name: "OutpostId"
          Value: !Ref SourceOutpostId
      Statistic: "Average"
      Period: 60
      EvaluationPeriods: 3
      DatapointsToAlarm: 3
      Threshold: 1
      ComparisonOperator: "LessThanThreshold"
      AlarmActions:
        - !Ref LambdaSNSTopic

Outputs:
  # Outputs will be dynamically inserted here